### ISSUE TITLE
write integration test for the 30 legistar sites

### ISSUE THREAD

**Issue by fgregg** [datamade/civic-scraper#11]
Using the list provided in #2, write an integration test script in the tests directory that makes sure that every legistar site will work.

It could look something like this

```python
for site, config in [list of (site, config):
    scraper = LegistarSite(site, config)
    data = scraper.scrape()
    assert len(data) > 10
```

**Comment by fgregg** [comment]
@fatima3558, let me know if you have any questions about this one!

**Comment by fatima3558** [comment]
@fgregg I broke down the steps for this since I couldn't quite visualize how I would make this happen:
- [ ] download the csv file with all the legistar sites (done, stored in `tests/fixtures` for now)
- [ ] Read the first 30 lines and get the legistar URL along with the state
- [ ] Using the state information, get the timezone which is the only kwarg I need to pass to the scraper
- [ ] use the loop you outlined in this issue to make sure the scraper works for each site

I'm a bit stuck on how I would get the 3rd step to work. I looked in the python docs and found [zoneinfo docs](https://docs.python.org/3/library/zoneinfo.html), which I think could be helpful, but I'm not sure how I would get from "CA" to "America/Los_Angeles", for example. Is this something I would just have to hardcode, or is there a better way to get from the state info to the timezone info programmatically?

**Comment by fgregg** [comment]
i would create the object you want and stuff it at the top of the file, and look up things up manually

for example:

```python
configs = [{'url': 'foo_bar', 'timezone': 'America/New York'},
           {'url': 'bar_foo', 'timezone': 'America/Chicago'}
           ...]

**Comment by fatima3558** [comment]
@fgregg working on this test, but it takes quite a long time to run; the `LegistarSite.scrape()` method takes a while for one legistar instance, let alone 30.. Is there anything I can look into doing to speed this test up?
